### ISSUE TITLE
程序只支持一级目录安装

### ISSUE THREAD

**Issue by CollageTomato** [HFO4/Cloudreve#1]
RT，经测试，程序只支持安装在一级目录下（如[https://sample.com](https://sample.com)），不支持多级目录（如[https://sample.com/cloudreve](https://sample.com/cloudreve)），如若安装于非一级目录，则会出现一些静态资源链接位置错误（如文件实际位置[https://sample.com/cloudreve/js.js](https://sample.com/cloudreve/js.js)，访问时却读取[https://sample.com/js.js](https://sample.com/js.js)，从而返回404），这可能是因为程序内文件链接使用了`./js.js`这样取一级目录的方式，如果这是你不愿意看见的事件，就在下个版本改善它吧！

eg: Cloudreve程序的完成度已经非常高了，我很希望它能越变越好！感谢你的贡献。

**Comment by HFO4** [comment]
会在未来版本修复

**Comment by Gaojianli** [comment]
请问修复了么？今天折腾了一天ORZ
