### ISSUE TITLE
额，上传传到99%不动是咋回事啊？

### ISSUE THREAD

**Issue by jiangxu1** [HFO4/Cloudreve#10]
如题，环境nginx1.12

**Comment by HFO4** [comment]
能不能提供下详细信息？至少要把上传策略类型说一下吧

**Comment by jiangxu1** [comment]
上传策略是默认的啊。没变过。上传时我看了F12，有报错。

**Comment by Rowingbohe** [comment]
那就应该把f12的报错贴出来啊（
按我经验估计是权限不够emm

**Comment by jiangxu1** [comment]
我正在贴呢。。。
![Uploading 2345截图20180211091532.png…](https://ww4.sinaimg.cn/large/0060lm7Tly1foc8qrxmcaj311s0jsjt2.jpg)

**Comment by jiangxu1** [comment]
权限不够？？？我TM是管理员账号上传啊，而且是默认上传策略啊。

**Comment by Rowingbohe** [comment]
加了Watching有点心急emm那个图里有个报错500
还有，我是说文件的权限，不是上传的。。。

**Comment by jiangxu1** [comment]
我知道。后台看过的啊。我去设置整个网站目录为777权限。试一试啊。

**Comment by jiangxu1** [comment]
OK，成功了啊。谢谢你了。
终于找到原因了。程序没有写入权限所以无法上传。
