### ISSUE TITLE
进不了管理后台

### ISSUE THREAD

**Issue by cjj7227** [HFO4/Cloudreve#100]
http://域名/Admin/UpdateDb
显示：
准备升级数据库，当前数据库版本:3, 目标数据库版本:4;
数据库更新文件(/域名/update_3to4.sql)不存在，升级中止.

**Comment by x-hezhang** [comment]
composer create-project hfo4/cloudreve:dev-master

**Comment by 619096932** [comment]
Could not find package hfo4/cloudreve with version dev-master.
