### ISSUE TITLE
希望丰富上传策略

### ISSUE THREAD

**Issue by Vckers** [HFO4/Cloudreve#106]
希望增加腾讯云COS和网易云NOS的上传策略

**Comment by Vckers** [comment]
还有希望新增管理员上传时可以选择想要的策略并且可以随意转换已上传文件的策略

**Comment by fantastlcok** [comment]
随意转化策略意味着转化的文件又要重新中转同步到其他储存，PHP不适合干这个。

**Comment by q14060** [comment]
加个腾讯的不错，

**Comment by q14060** [comment]
加个腾讯的不错，

**Comment by HFO4** [comment]
https://github.com/HFO4/Cloudreve/issues/76
