### ISSUE TITLE
升级用户组页面点击“立即购买”按钮后modal不自动消失

### ISSUE THREAD

**Issue by cytvictor** [HFO4/Cloudreve#11]
![screen shot 2018-02-11 at 7 21 03 pm](https://user-images.githubusercontent.com/13085122/36072781-e1ef1d26-0f60-11e8-9ec7-3a8db7ff622f.png)
如图

**Comment by cytvictor** [comment]
或者说还没写好，233333 那是不是提issue太早了

**Comment by HFO4** [comment]
实际上已经修复了，演示站还没更新
