### ISSUE TITLE
文件分享页面优化建议

### ISSUE THREAD

**Issue by fcwys** [HFO4/Cloudreve#116]
建议分享页面的文件直接点击就可以下载而不需要右键点击或长按(移动端)，若是目录点击打开。感觉这个会方便很多，而且移动端列表模式长按几乎无法使用，希望能改进下，谢谢
![image](https://user-images.githubusercontent.com/28641034/50260876-e4894780-0444-11e9-9118-e377f3b7b64c.png)

**Comment by HFO4** [comment]
下个版本前端会进行重构
