### ISSUE TITLE
搭建好后打开任何网页都是首页界面，望大佬帮忙解决

### ISSUE THREAD

**Issue by jianhua0209** [HFO4/Cloudreve#127]

**Comment by jianhua0209** [comment]
---------------------------------------------------------------
[ 2019-01-20T20:00:46+08:00 ] 122.114.220.212 122.114.134.27 GET /Home
[ error ] [2002]SQLSTATE[HY000] [2002] Connection refused
---------------------------------------------------------------
[ 2019-01-20T20:00:56+08:00 ] 122.114.220.212 122.114.134.27 GET /
[ error ] [2002]SQLSTATE[HY000] [2002] Connection refused
---------------------------------------------------------------
[ 2019-01-20T20:00:58+08:00 ] 122.114.220.212 122.114.134.27 GET /
[ error ] [2002]SQLSTATE[HY000] [2002] Connection refused
---------------------------------------------------------------
[ 2019-01-20T20:05:46+08:00 ] 122.114.220.212 122.114.134.27 GET /
[ error ] [2002]SQLSTATE[HY000] [2002] Connection refused
---------------------------------------------------------------
[ 2019-01-20T20:06:23+08:00 ] 122.114.220.212 122.114.134.27 GET /Member
[ error ] [2002]SQLSTATE[HY000] [2002] Connection refused

**Comment by HFO4** [comment]
检查下伪静态规则
