### ISSUE TITLE
高CPU占用率 $ 持续访问自己的ip/域名

### ISSUE THREAD

**Issue by 1349422030** [HFO4/Cloudreve#129]
![default](https://user-images.githubusercontent.com/35253997/51783883-c4ebea00-217b-11e9-8d43-d6fcec3a4931.png)
* 如图所示，一直保持１５左右的CPU占用率，当我禁止非中国ｉｐ登陆后，发现大量ｉｐ访问ｃｌｏｕｄｒｅｖｅ的域名，而这个ｉｐ全部都是`服务器自己的ｉｐｖ６地址`，而且禁止访问后CPU女佣女明显下降（见中间的一段低谷）

* 开始怀疑是aria2，但是发现我写的配置直接指定了ip，不应该通过域名去访问，所以感觉很奇怪
。测试发现，禁止非大陆ip访问后离线下载并未受影响，此外，我发现图片缩略图一直都是撕裂状态，请问这里是哪一步需要修改？（所有环境检查都是通过）
![default](https://user-images.githubusercontent.com/35253997/51783926-712dd080-217c-11e9-9842-9bff12e15fd7.png)

**Comment by 1349422030** [comment]
我刚刚关闭了OneDrive上传策略（反正做到最后才发现不支持世纪互联😂），但是情况依旧存在。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: AaronLiu <notifications@github.com>
发送时间: Saturday, January 26, 2019 3:24:11 PM
收件人: HFO4/Cloudreve
抄送: 1349422030; Author
主题: Re: [HFO4/Cloudreve] 高CPU占用率 $ 持续访问自己的ip/域名 (#129)


是不是使用了Onedrive策略？如果是的话，把任务队列轮询间隔调大即可。

**Comment by HFO4** [comment]
那只有可能是cron每分钟查询离线下载进度的请求了，能不能看到请求的URL呢

**Comment by 1349422030** [comment]
查到了，是Queue。

URI /Queue/getList?num=1



发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: AaronLiu <notifications@github.com>
发送时间: Monday, January 28, 2019 10:44:47 AM
收件人: HFO4/Cloudreve
抄送: 1349422030; Author
主题: Re: [HFO4/Cloudreve] 高CPU占用率 $ 持续访问自己的ip/域名 (#129)


那只有可能是cron每分钟查询离线下载进度的请求了，能不能看到请求的URL呢

―

**Comment by HFO4** [comment]
可以适当增大队列的查询间隔
