### ISSUE TITLE
管理员离线下载页面请坐和放宽

### ISSUE THREAD

**Issue by 1349422030** [HFO4/Cloudreve#130]
概况如图
![default](https://user-images.githubusercontent.com/35253997/51850750-55cdeb80-235d-11e9-8efc-f56d20fded35.png)
我在此之前做的最后一个操作是在管理离线下载的页面修改路径为/var/aria2,down，其他的emmm,还有一个好像并无卵用的日志
172.68.253.85 - - [29/Jan/2019:00:34:10 +0800] "GET /Admin/RemoteDownload HTTP/1.1" 500 7311 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0"

**Comment by HFO4** [comment]
已在https://github.com/HFO4/Cloudreve/commit/df8581e2388357cbae5cdc204478a8e7ead62e31 修复
