### ISSUE TITLE
Cron 很抱歉,出现错误 :(

### ISSUE THREAD

**Issue by Zhangzijing** [HFO4/Cloudreve#133]
日志:
[ error ] [0]不支持的数据表达式:`rank`

**Comment by Zhangzijing** [comment]
CronHandler.php
Line20: 
```php
		$this->cornTasks = Db::name('corn')->where('enable',1)->order('`rank` desc')->select();
```
改:
```php
		$this->cornTasks = Db::name('corn')->where('enable',1)->order('rank desc')->select();
```
问题解决.

环境: php 7.2(nginx+php-fpm) + CentOS7 + MySQL 5.6.42

**Comment by HFO4** [comment]
已在https://github.com/HFO4/Cloudreve/commit/564578aefb93ab565f97146077c7e791ce57d426 修复
