### ISSUE TITLE
如何以socket方式连接mysql

### ISSUE THREAD

**Issue by JadeVane** [HFO4/Cloudreve#139]
由于mysql使用的是socket方式运行，请问如何填写`application/database.php`配置文件？

**Comment by cytvictor** [comment]
以 DSN 方式进行连接，在 DSN 字段中加入 ```unix_socket=/path/to/your/socket.sock``` 即可。
参考 ThinkPHP 数据库连接配置 https://www.kancloud.cn/manual/thinkphp5/118059

**Comment by JadeVane** [comment]
@cytvictor 可以了，谢谢
