### ISSUE TITLE
能把程序引用的静态文件添加bootCDN吗？

### ISSUE THREAD

**Issue by jiangxu1** [HFO4/Cloudreve#14]
如题：引用的jQuery啦，等等一些静态文件，可以添加一些前端CDN库啊。
我原来自己修改的文件，一上传升级包就全部覆盖了。

**Comment by HFO4** [comment]
考虑到有些用户是纯内网环境，原则上不会使用cdn，你可以自己修改后更新时注意备份

**Comment by jiangxu1** [comment]
那我每次更新怎么办啊。还是希望在后头设置中添加一下啊。
例如：静态文件引用：1.本地读取   2.XX前端CDN库。（单选框即可啊）
这样不是很好嘛？也不会多多少代码啊。就是一个变量判断的问题啊。
