### ISSUE TITLE
安装完二步验证支持库后仍然不显示二维码

### ISSUE THREAD

**Issue by dsjwu** [HFO4/Cloudreve#17]
安装完之后仍然不显示是什么原因呢

**Comment by HFO4** [comment]
看下`runtime`目录下的错误日志

**Comment by dsjwu** [comment]
![image](https://user-images.githubusercontent.com/36589843/36350131-48f07d82-14cd-11e8-8a1e-09ddbca033ed.png)
这个吗？你看一下

**Comment by HFO4** [comment]
还是依赖没装好。
```
composer require phpgangsta/googleauthenticator:dev-master
composer require endroid/qrcode
```

**Comment by HFO4** [comment]
已在https://github.com/HFO4/Cloudreve/pull/18 修复
