### ISSUE TITLE
无法使用阿里云OSS作为存储桶

### ISSUE THREAD

**Issue by oniya123** [HFO4/Cloudreve#21]
通过东京的AWS搭建了cloudreve
添加阿里云oss上传后卡在100%，但阿里云存储桶内无内容
尝试过使用其他地区的存储桶，例如东京和新加坡地区均无法上传
但七牛云工作正常
检查过所有配置均无异常

**Comment by HFO4** [comment]
F12看下怎么报错

**Comment by oniya123** [comment]
![image](https://user-images.githubusercontent.com/30280837/36369757-67d2bbdc-1597-11e8-89f0-5fd87ce0ef7f.png)

**Comment by oniya123** [comment]
![image](https://user-images.githubusercontent.com/30280837/36369792-8dec8ac8-1597-11e8-94e8-6df675ae3aa2.png)

**Comment by HFO4** [comment]
上传策略的那几个域名前面都要加上http(s)

**Comment by oniya123** [comment]
加上后提示http错误

**Comment by HFO4** [comment]
具体什么错误？

**Comment by oniya123** [comment]
上传页面显示HTTP错误，我不太懂，需要f12吗

**Comment by oniya123** [comment]
![image](https://user-images.githubusercontent.com/30280837/36370387-a9c61b54-1599-11e8-8a83-3c900e2c8126.png)
如图设置后上传还是HTTP错误
![image](https://user-images.githubusercontent.com/30280837/36370436-d154acb2-1599-11e8-9a6e-76c74528101c.png)

**Comment by HFO4** [comment]
来源和header填写为`*`
另可参阅https://forum.cloudreve.org/d/3

**Comment by oniya123** [comment]
上传成功，但无法预览和下载文件，提示"Error 500 - 请求失败，登录可能已过期，请重新登陆"

**Comment by oniya123** [comment]
下载时报错信息：Can not override response header for an anonymous user
![image](https://user-images.githubusercontent.com/30280837/36371005-c5e9263a-159b-11e8-93b9-28352a2cb10b.png)

**Comment by oniya123** [comment]
Hi？

**Comment by HFO4** [comment]
去论坛讨论吧
