### ISSUE TITLE
会员中心内显示的容量与后台设定的用户组容量不相符

### ISSUE THREAD

**Issue by dsjwu** [HFO4/Cloudreve#25]
我设定的注册会员最大容量为3GB，在前台注册会员后会员中心内显示的容量为1.99GB，如下图：
![image](https://user-images.githubusercontent.com/36589843/36515802-127f9788-17b6-11e8-837d-dc9fa45a471a.png)
![image](https://user-images.githubusercontent.com/36589843/36515825-3073ef6e-17b6-11e8-9627-b19dc272401b.png)

**Comment by HFO4** [comment]
能提供下你的站点URL吗

**Comment by dsjwu** [comment]
pan.dsjwu.com
