### ISSUE TITLE
上传的视频无法预览

### ISSUE THREAD

**Issue by dsjwu** [HFO4/Cloudreve#26]
上传的视频无法预览，用的阿里云OSS做的存储，能下载，但是无法预览

**Comment by dsjwu** [comment]
在分享页能够预览，在个人文件内无法预览

**Comment by HFO4** [comment]
没法复现。能不能把你的上传方案截下图、视频文件分享一下我看下

**Comment by dsjwu** [comment]
不知怎么传不上来图了，上传策略绝对没有问题
视频文件分享地址：http://pan.dsjwu.com/s/3zqsiq2q

**Comment by HFO4** [comment]
上传策略是什么类型的？另外能不能把f12控制台截图贴出来

**Comment by tuzi3040** [comment]
在文件分享页预览时，
播放视频，然后直接点击右上角的 x ，预览窗口关闭，但音频仍在播放。
重新进入预览窗口，音频停止播放。
似乎是关闭窗口时控件转入后台运行，然后重新进入又重载了？。。。
希望fix一下。

**Comment by dsjwu** [comment]
用的阿里云OSS，F12控制台截图如下：
![f12](https://user-images.githubusercontent.com/36589843/36717042-7b3367d0-1bd7-11e8-9ec3-6bbf9de53a5b.png)

**Comment by fcwys** [comment]
您好，我使用阿里云oss上传一直报错，不知道什么原因，希望能给个建议，谢谢!
