### ISSUE TITLE
Windows 10 添加 WebDAV

### ISSUE THREAD

**Issue by StringKe** [HFO4/Cloudreve#37]
Windows 10 添加网络位置后 打开该文件夹为空 直接通过浏览器访问 地址登陆后却可以查看文件

![image](https://user-images.githubusercontent.com/31089228/36966927-4d393406-2099-11e8-9ab5-a4f4f211a022.png)

**Comment by StringKe** [comment]
![image](https://user-images.githubusercontent.com/31089228/36967847-d057515e-209b-11e8-968b-9f552ffdf10b.png)

**Comment by HFO4** [comment]
目前WebDAV仅支持本地策略

**Comment by StringKe** [comment]
本地策略? 如何使用呢?

**Comment by HFO4** [comment]
本地的话也是这个报错？能否给个测试账号呢
