### ISSUE TITLE
可以考虑整合DigitalOcean的对象存储吗？

### ISSUE THREAD

**Issue by helloxz** [HFO4/Cloudreve#41]
原因如下：
* 国内的对象存储免费额度有限，超过之后流量不便宜。
* DigitalOcean对象存储可以免费用2个月
* 5$/月，250 GB的存储空间， 1 TB流量，配合国外VPS使用效果极佳，无论是存大文件还是大流量下载都是不错的选择。
* 参考：https://www.digitalocean.com/products/spaces/ 
期望得到答复。

**Comment by HFO4** [comment]
我这几天看下他们的文档，如果能达到基本要求就会对接

**Comment by huanjue** [comment]
其实就是AMAZON S3的API，改下API地址就可以用了。包括secretkey等等都是与s3保持同步的（官方为了便于迁移）。

**Comment by helloxz** [comment]
谢谢提醒，看了DO的文档确实是兼容S3的。
