### ISSUE TITLE
关于程序安装

### ISSUE THREAD

**Issue by fcwys** [HFO4/Cloudreve#43]
希望作者能做成直接上传到网站根目录就有安装向导安装的，装composter弄不来，希望考虑下呢，很需要这个东西但又不太会用，能用的话会一直支持作者呢，衷心希望cloudreve越来越好。

**Comment by HFO4** [comment]
可以在 cloudreve.org 下载安装包，已安装所有依赖，不需要composer

**Comment by fcwys** [comment]
我直接上传到网站根目录访问报错，不知道啥原因
环境：
php7.0
mysql5.5
nginx
