### ISSUE TITLE
分享页面下载页优化

### ISSUE THREAD

**Issue by fcwys** [HFO4/Cloudreve#44]
1.分享页面下载页需右键点击，希望直接点击就能下载。
2.我的文件下需双击进入文件夹内，希望单击即可进入。
希望cloudreve越来越好

**Comment by fcwys** [comment]
macbook点击分享文件无反应

**Comment by HFO4** [comment]
@fcwys 直接说，浏览器是？

**Comment by fcwys** [comment]
Safari和火狐

**Comment by HFO4** [comment]
@fcwys 是右键文件的那个分享对吗

**Comment by fcwys** [comment]
嗯呢，点击双击都没反应，建议直接点击下载最好呢

**Comment by fcwys** [comment]
![00000](https://user-images.githubusercontent.com/28641034/37812915-9b8728c2-2e9d-11e8-8f1d-05d205d24bad.png)
jiu就这个页面呢
