### ISSUE TITLE
点击文件/文件夹不出现菜单

### ISSUE THREAD

**Issue by sxjeru** [HFO4/Cloudreve#47]
PC，Chrome：65.0.3325.181 x64
单击一次文件/文件夹选定，再点击一次除了变黑，没有菜单出现。
![image](https://user-images.githubusercontent.com/20513115/37872077-e0ccb25e-3031-11e8-9df4-c3ccef09e692.png)
安卓端可用。

**Comment by HFO4** [comment]
右键

**Comment by sxjeru** [comment]
右键仅有系统菜单。
![image](https://user-images.githubusercontent.com/20513115/37872088-3957f320-3032-11e8-9e58-734d219c1095.png)

**Comment by sxjeru** [comment]
好吧抱歉打扰了，开了这个。
![image](https://user-images.githubusercontent.com/20513115/37872091-6ef4843a-3032-11e8-9bbb-0e4a1cf16fd6.png)
