### ISSUE TITLE
分享页面视频全屏后只有半个屏幕

### ISSUE THREAD

**Issue by gakiyuibo** [HFO4/Cloudreve#49]
@HFO4

**Comment by morinoyuki** [comment]
"\static\js\share_single.js"
`$(".previewContent").html('<div id="preview-target" style="width: 100%;object-fit: fill;height:400px" class="preview"></div>');`
改成
`$(".previewContent").css("height", "400px");
$(".previewContent").html('<div id="preview-target" style="width: 100%;object-fit: fill;" class="preview"></div>');`

**Comment by HFO4** [comment]
新版中已无此问题
