### ISSUE TITLE
是否支持B2存储？

### ISSUE THREAD

**Issue by zhanggaoxuan** [HFO4/Cloudreve#5]
是否支持backblaze存储？
另外对接对象存储的话控制限额功能是否能生效？

**Comment by HFO4** [comment]
对接云存储限额也是生效的，b2暂时不支持

**Comment by zhanggaoxuan** [comment]
有对接b2的计划么？b2便宜的多。。

**Comment by HFO4** [comment]
我刚刚也才看他们的文档，但不能确保可以对接，因为他们的api可能达不到需求，比如无法限制文件大小等。
我还在看文档，待会确认了告诉你

**Comment by HFO4** [comment]
很可惜，目前来看是对接不了的

**Comment by zhanggaoxuan** [comment]
好吧，那我还是等等吧~

**Comment by HFO4** [comment]
今天又仔细看了下 ，是可以对接的,但是有一定局限，仅能作为私有云使用的策略。我这几天会尝试对接下。

**Comment by zhanggaoxuan** [comment]
好的，其实还可以考虑一种思路，比如支持同时对接多个云存储，允许分配给不同用户，比如不需要限额的账户，分配b2过去，需要限额的子用户，分配阿里oss过去，这样就实现了混合的方案

**Comment by HFO4** [comment]
现在就支持，不同用户组可以使用不同上传策略

**Comment by zhanggaoxuan** [comment]
那就好，等后期b2有了限制额度的API，就更加方便了

**Comment by HFO4** [comment]
目前遇到了瓶颈。B2的upload api中规定：

> The following HTTP headers must not be included in the b2_upload_file request:
>*  Cache-Control
>* ………

目前尚未找到移除xhr请求默认header的方法.

**Comment by zhanggaoxuan** [comment]
可以看看https://www.duplicati.com/他们是如何处理的，已经对接了B2的，而且也是开源的

**Comment by HFO4** [comment]
duplicati是桌面客户端吧？这样header就很好控制，但是Cloudreve是网页端直传。B2对接先暂停了，等找到有效方法再继续。

**Comment by zhanggaoxuan** [comment]
嗯，桌面客户端，通过web界面设置规则。
其实你也可以考虑出个客户端的。就像nextcloud一样，网页和客户端均支持。

另外，版本记录是个很好的功能。

顺路说一句，你的官网，在北京联通的部分网络环境下，打不开。

**Comment by fantastlcok** [comment]
b2 真的便宜，我觉得像Onedrive那样中转下都行。

**Comment by zhanggaoxuan** [comment]
> b2 真的便宜，我觉得像Onedrive那样中转下都行。

而且现在和cloudflare集成以后，不用流量费了
