### ISSUE TITLE
分享文件夹提示 "该文件夹没有文件"

### ISSUE THREAD

**Issue by Indexyz** [HFO4/Cloudreve#6]
分享了一个内有文件的文件夹 但是打开该分享链接的时候提示该文件夹内无文件

通过 Chrome Devtools 查看 filemanager 的ajax请求 发现服务端返回的JSON为
```json
[false, "分享不存在，请检查链接是否正确"]
```
但是在管理面板查看的确有此分享链接 并且在分享页面上也有显示分享用户的用户名和头像

## 服务端环境
Commit: https://github.com/HFO4/Cloudreve/commit/47f334b6f4cb8c5badb5d020b27c30d824b88dd6
PHP: 7.1.14

**Comment by HFO4** [comment]
感谢反馈 已在https://github.com/HFO4/Cloudreve/commit/63cc404d7482f696bcb547e690a85c251b5aec9d 修复
