### ISSUE TITLE
用官网安装包,后台正常,首页进去报错

### ISSUE THREAD

**Issue by fl20002** [HFO4/Cloudreve#60]
![1](https://user-images.githubusercontent.com/18693963/38594433-ca1a6e62-3d78-11e8-9084-fc94a7dd0a69.png)

**Comment by HFO4** [comment]
请使用序号35前的开发版安装包或使用稳定版

**Comment by fl20002** [comment]
用了稳定版  很不错  
再请教下 
OSS的空间域名和上传域名填写
http://my-Bucket.oss-cn-hongkong.aliyuncs.com/
提示错误
应该怎么填写?
