### ISSUE TITLE
视频预览推荐使用 DPlayer

### ISSUE THREAD

**Issue by DIYgod** [HFO4/Cloudreve#7]
不仅是播放器体验更好，其中的流媒体支持和加速播放对视频预览也有很大帮助

https://github.com/MoePlayer/DPlayer

**Comment by HFO4** [comment]
好的好的,这个安利接受了😉

**Comment by HFO4** [comment]
已经在https://github.com/HFO4/Cloudreve/commit/d2ca69b945d4fa12a8b0362ee88f2afb27bf229a 初步完成，但是flv预览还有点问题，working on it.

**Comment by HFO4** [comment]
emmm 找到原因了。flv.js fetch视频数据的时候没有携带cookie，被服务端拒绝了

**Comment by HFO4** [comment]
暂时无解，姑且先不支持flv

**Comment by liwanglin12** [comment]
当然选择自行魔改 flv.js 或者给那边发 issue 啦（
