### ISSUE TITLE
注册邮件被QQ邮箱认为垃圾邮件

### ISSUE THREAD

**Issue by hiCasper** [HFO4/Cloudreve#71]
使用了Sendgrid发送邮件，所以服务器方面应该不存在问题。以下是SpamAssasin的评分：
![QQ截图20180511232332.jpg](https://i.loli.net/2018/05/11/5af5b587b369b.jpg)

**Comment by HFO4** [comment]
暂时可通过自定义邮件模板改善下

**Comment by Gaojianli** [comment]
@HFO4 怎么改善啊
