### ISSUE TITLE
上传速度最高只有200KB/s

### ISSUE THREAD

**Issue by DearTanker** [HFO4/Cloudreve#72]
我使用的宝塔面板，LAMP环境，全默认配置环境。

安装好Cloudreve以后上传速度最高只能200KB/S，带宽上行是10M的，测速都正常。宝塔后台的文件管理上传速度也正常。确保排除了上行带宽有问题。

我想问的是，是不是有哪些地方是需要优化的。希望可以指点一下。

**Comment by HFO4** [comment]
上传速度和程序本身无关

**Comment by DearTanker** [comment]
我当然知道和程序无关了，只是想请教一下怎么优化呀。
