### ISSUE TITLE
七牛云 请求报文格式错误。(400：token not specified)

### ISSUE THREAD

**Issue by 6ke** [HFO4/Cloudreve#78]
请教下这个报错是什么问题

下面是我上传策略填的参数
https://sheui.oss-cn-shanghai.aliyuncs.com/20180524/6/6_20180524095415_20180524095326.png

**Comment by HFO4** [comment]
ak或sk有误

**Comment by 6ke** [comment]
@HFO4 感谢回复。 我新建了ak 。sk ，认真填写了 传 png 图还是这个错误；传其他格式文件有一点点进度条了 然后就跳 “ 客户端认证授权失败。请重试或提交反馈。(401：bad auth) ”   错误
