### ISSUE TITLE
部分直链文件的文件名被重命名

### ISSUE THREAD

**Issue by mankezhou** [HFO4/Cloudreve#79]
![20180525164919](https://user-images.githubusercontent.com/39617667/40535464-c95ed676-603b-11e8-9256-d7a0e2a210f3.png)

感觉是随机性的被重命名了

**Comment by HFO4** [comment]
疑似bug，具体是哪种上传方案呢？

**Comment by HFO4** [comment]
可在上传策略-编辑中的命名规则，`{originname}`中原文件名的后缀和程序自己加的重复了，暂时不会修改，可以通过去掉`{originname}`避免此现象
