### ISSUE TITLE
开启X-Sendfile模式后的下载问题

### ISSUE THREAD

**Issue by Yuanuo** [HFO4/Cloudreve#80]
nginx环境，使用x-sendfile模式后，在Response Headers中返回的Content-type总是“text/html”，导致浏览器识别为HTML格式的内容。
虽然Chrome和Firefox会根据content-disposition中指定的附件名来保存，但识别到的内容格式仍然是HTML，比如下载一个doc文件时Firefox会提示为“Firefox Document”。
如果是Safari浏览器，它会在下载的时候在附件名后面加上“.html”，比如下载一个doc，最后保存的却是“xxx.doc.html”，导致以html格式打开doc而显示乱码。

请修复一下，谢谢。

**Comment by 1599947920** [comment]
如何开启？

**Comment by 1599947920** [comment]
php拓展中没找到

**Comment by Yuanuo** [comment]
系统管理员在前端控制台中可开启。

Fixed by #89
