### ISSUE TITLE
又拍云接口上传成功后依旧没有显示文件

### ISSUE THREAD

**Issue by Ice-Hazymoon** [HFO4/Cloudreve#84]
upyun接口配置全部正确, 文件也传到upyun里了, 前端也提示上传成功, 但却没有显示在文件列表里, 后台管理界面也显示文件数为0

**Comment by Ice-Hazymoon** [comment]
以解决, 执行一次定时任务即可, 但上传成功后要手动刷新一次页面才能显示新的文件

**Comment by HFO4** [comment]
@Ice-Hazymoon 暂时无解，upyun的回调是异步的
