### ISSUE TITLE
无法离线下载

### ISSUE THREAD

**Issue by 1424753988** [HFO4/Cloudreve#85]
操作时 提示： 您当前的无用户无法执行此操作
这句什么意思啊，感觉这句话本身都有问题，念不通。

**Comment by Zxilly** [comment]
应该是你用低权限用户跑了Cloudreve.
话不能这么看，这里的无指的是null吧

**Comment by HFO4** [comment]
这句话是病句，感谢反馈。
请确保用户组设置里允许离线下载，并且为本地策略。
