### ISSUE TITLE
希望添加aria2离线下载支持

### ISSUE THREAD

**Issue by gaojianye** [HFO4/Cloudreve#9]
现在用nextcloud可以支持aria2 但是对流量和空间无法限制。希望作者可以支持，可以提供已搭建好的aria2测试

**Comment by HFO4** [comment]
暂时无对接计划，请关注后续更新

**Comment by HFO4** [comment]
大概确定会在下一个大更新中加入

**Comment by HFO4** [comment]
已在https://github.com/HFO4/Cloudreve/commit/36e6526259a5838833e83dd190b2aa5f5582d9f1 实现
