### ISSUE TITLE
文件存放方式的一些建议

### ISSUE THREAD

**Issue by sang8052** [HFO4/Cloudreve#98]
//并未详细阅读源代码，仅提出一些建议
1.文件真实下载链接的隐藏。能否利用时间戳，用户名，密钥等构建文件的临时下载地址。文件存放在本地的情况我没有操作。七牛上是有私有权限的空间的，可以考虑一下
2.文件名的重名问题。我自己也写过一个小型的网盘系统，对接的是腾讯COS，一开始我是把所有用户的文件文件都保存在一个文件夹下面，同时文件名不做更改（需求中不允许更改文件名）。目前使用的逻辑是每个用户创建一个文件夹保存数据，用户的每一个文件会存放在名为数据库中的“虚拟逻辑地址+文件名+时间“MD5值文件夹下面，用户需要下载打开文件的时候通过地址拼接（有临时密钥戳）来实现下载。
3.文件秒传 能够根据文件的MD5值建立索引，如果文件的MD5值相同，只是文件存储的路径不同时（文件的所有用户不同）时，通过修改数据库中虚拟逻辑地址对应的真实地址的方式实现文件秒传
4.如果有可能，作者可通过定期向自己的核心服务器上上传用户文件的MD5值和路径，从而形成多点网络，优化数据上传，提高秒传能力

**Comment by HFO4** [comment]
感谢您的建议
1. 目前除了本地策略以外，其他上传策略的下载地址都是签名后的临时地址。本地的后续会完善此功能
2. 可通过设置存储目录规则避免重名。
3. 秒传需要客户端和服务端计算Hash，资源消耗较大，暂时不考虑开发
4. 同上述
